Vagrant.configure('2') do |config|

  config.vagrant.plugins = 'vagrant-libvirt'
  
  config.vm.box = 'generic/debian11'
  config.vm.provision :shell, path: 'provision.sh'
  config.vm.synced_folder '.', '/vagrant', type: 'rsync'

  config.vm.provider :libvirt do |libvirt|

    libvirt.qemu_use_session = false

    libvirt.cpus = 4
    libvirt.memory = 8192
    libvirt.video_vram = 128

    libvirt.video_type = 'virtio'
    libvirt.graphics_type = 'spice'

    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
    libvirt.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'

  end

end
